[0m22:14:41.785738 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107cb9e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a13c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a13ed0>]}


============================== 22:14:41.788962 | e9434dc4-9d8d-49aa-94d8-d5fd73535f7a ==============================
[0m22:14:41.788962 [info ] [MainThread]: Running with dbt=1.9.0
[0m22:14:41.789340 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/ramana/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:14:41.789678 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ramana/github_repos/analytics-projects/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:14:41.816109 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07427534, "process_in_blocks": "0", "process_kernel_time": 0.142537, "process_mem_max_rss": "104218624", "process_out_blocks": "0", "process_user_time": 0.712437}
[0m22:14:41.816563 [debug] [MainThread]: Command `dbt run` failed at 22:14:41.816486 after 0.07 seconds
[0m22:14:41.816818 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1089236f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088ab890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ab4380>]}
[0m22:14:41.817060 [debug] [MainThread]: Flushing usage events
[0m22:14:42.528329 [debug] [MainThread]: An error was encountered while trying to flush usage events
